language: go
notifications:
  email: false
  slack:
    rooms:
      secure: TY6bKscdBn1ist96VGPzgHRH0NLs0ES0D0xG98m8LmeRUHVjIGvOJDxhpoe/U6B6RpYwBGMmD8SpJxp4sKBEhu+SkpwJ4KKAm5bM1dOG6An51k3Iu6XS32hgFDw6evMOeaCaoUbUFyGtKsUQB2BsaTi4S742ZtU4akCC29nsvN28QPCnij5/jE3176t5QZxR1VtuJw2TEUTbP7ZjUC5EKBSsFQuUSno78M628Xub4bT/51wdfNQrCRjMLL6sqhPa/2DZzWnBMcZs7yQ8eqvTC/MK1chz4tI5iFp82w6dl5BsN4o4fff+jDllfANoCiQoSOxXyMR4DLtUfSk+hEVAx7EAwxnX2K4+9/pGvejjABoTh4+m6fu/qAqp8vto0B1//1yc5GuaWas7OldL959SZd4MJR1tLZ1OWBdldf1tjA15NJ6js4319U1ky8nNMQ17x4mre7t9GOTboEA6npH4bJhT4UGBmi1LC46f0NsvDPaEtghpyedbHjH4TG2KvptxGSOu071fsqbpimjj2X0vYYlFqzppOm94jNyyIcoaBTPNjXUx3F8XKoyrJD/f1jdaJi3EzQfrxSkIG4J6P0sEprivyThah12Jsm5YD50PfHSiJ+BSKhl/PdtKfgBRTMyw6Y3uI1R+zQzkY5PNRr/ORMrXRadnlKVo1W8Di4z6o/I=
